#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Clawttack Hermes Agent — Docker Entrypoint
#
# Sequence:
#   1. Configure Hermes .env with model + API key from Docker env
#   2. Start Hermes Gateway (API server on port 8642)
#   3. Wait for it to be healthy
#   4. Run the Clawttack battle
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${CYAN}[hermes]${NC} $*"; }
ok()   { echo -e "${GREEN}[hermes]${NC} $*"; }
warn() { echo -e "${YELLOW}[hermes]${NC} $*"; }
err()  { echo -e "${RED}[hermes]${NC} $*"; }

# ── Config ────────────────────────────────────────────────────────────────────
BATTLE_STRATEGY_A="${BATTLE_STRATEGY_A:-hermes}"
BATTLE_STRATEGY_B="${BATTLE_STRATEGY_B:-smart-script}"
BATTLE_ROUNDS="${BATTLE_ROUNDS:-1}"
RPC_URL="${RPC_URL:-http://127.0.0.1:8545}"
HERMES_API_PORT="${HERMES_API_PORT:-8642}"

# Model defaults — user can override via env
HERMES_MODEL="${HERMES_MODEL:-openrouter/auto}"
OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"

# ── Step 1: Configure Hermes .env ─────────────────────────────────────────────
info "Configuring Hermes Agent..."
HERMES_HOME="${HERMES_HOME:-/root/.hermes}"
mkdir -p "$HERMES_HOME"

# Write .env for the Hermes agent runtime
cat > "$HERMES_HOME/.env" << ENVEOF
# Auto-generated by Clawttack entrypoint
HERMES_MODEL=${HERMES_MODEL}
ENVEOF

# Pass through any available LLM keys
[ -n "$OPENROUTER_API_KEY" ] && echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}" >> "$HERMES_HOME/.env"
[ -n "$OPENAI_API_KEY" ] && echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> "$HERMES_HOME/.env"
[ -n "$ANTHROPIC_API_KEY" ] && echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" >> "$HERMES_HOME/.env"

ok "Model: ${HERMES_MODEL}"

# ── Step 2: Show skills ──────────────────────────────────────────────────────
info "Loaded skills:"
hermes skills list 2>/dev/null || warn "Skill listing failed (non-fatal)"

# ── Step 3: Start Hermes Gateway ──────────────────────────────────────────────
info "Starting Hermes Gateway (API server on port ${HERMES_API_PORT})..."

# Run gateway in foreground, log to stderr
hermes gateway run 2>&1 | sed 's/^/[hermes-gw] /' &
GATEWAY_PID=$!

# ── Step 4: Wait for health ───────────────────────────────────────────────────
info "Waiting for Hermes API server..."
MAX_WAIT=30
ELAPSED=0
while [ $ELAPSED -lt $MAX_WAIT ]; do
  if curl -sf "http://127.0.0.1:${HERMES_API_PORT}/health" > /dev/null 2>&1; then
    ok "✅ Hermes API server is healthy on port ${HERMES_API_PORT}"
    break
  fi
  sleep 1
  ELAPSED=$((ELAPSED + 1))
done

if [ $ELAPSED -ge $MAX_WAIT ]; then
  warn "Hermes Gateway did not start within ${MAX_WAIT}s"
  warn "hermes.ts will fall back to direct OpenRouter calls"
fi

# ── Step 5: Resolve deployment addresses ──────────────────────────────────────
DEPLOY_FILE="/workspace/packages/abi/deployments/local.json"
if [ -f "$DEPLOY_FILE" ]; then
  info "Found local deployment at ${DEPLOY_FILE}"
  ARENA_ADDRESS="${ARENA_ADDRESS:-$(python3 -c "import json; d=json.load(open('$DEPLOY_FILE')); print(d['contracts']['arena'])" 2>/dev/null || echo '')}"
  [ -n "${ARENA_ADDRESS:-}" ] && info "Arena: ${ARENA_ADDRESS}"
fi

# ── Step 6: Run battle ────────────────────────────────────────────────────────
ok "Starting battle: ${BATTLE_STRATEGY_A} vs ${BATTLE_STRATEGY_B} (${BATTLE_ROUNDS} round(s))"
info "RPC: ${RPC_URL}"
info "Agent API: http://127.0.0.1:${HERMES_API_PORT}/v1"

exec bun /workspace/scripts/agent/run-battle.ts \
  --a "${BATTLE_STRATEGY_A}" \
  --b "${BATTLE_STRATEGY_B}" \
  --rounds "${BATTLE_ROUNDS}"
