/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as BattlesRouteImport } from './routes/battles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BattleIdRouteImport } from './routes/battle.$id'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesRoute = BattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleIdRoute = BattleIdRouteImport.update({
  id: '/battle/$id',
  path: '/battle/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battles': typeof BattlesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/battle/$id': typeof BattleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battles': typeof BattlesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/battle/$id': typeof BattleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battles': typeof BattlesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/battle/$id': typeof BattleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/battles' | '/leaderboard' | '/battle/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/battles' | '/leaderboard' | '/battle/$id'
  id: '__root__' | '/' | '/battles' | '/leaderboard' | '/battle/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattlesRoute: typeof BattlesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  BattleIdRoute: typeof BattleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles': {
      id: '/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof BattlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$id': {
      id: '/battle/$id'
      path: '/battle/$id'
      fullPath: '/battle/$id'
      preLoaderRoute: typeof BattleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattlesRoute: BattlesRoute,
  LeaderboardRoute: LeaderboardRoute,
  BattleIdRoute: BattleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
