//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ClawttackArena
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const clawttackArenaAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_wordDictionary', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    inputs: [],
    name: 'DEFAULT_ELO_RATING',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_CREATION_FEE',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_ELO_DIFF',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_JOKERS',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_PROTOCOL_FEE_RATE',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_REGISTRATION_FEE',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_WARMUP_BLOCKS',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MIN_RATED_STAKE',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MIN_WARMUP_BLOCKS',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'vopAddress', internalType: 'address', type: 'address' }],
    name: 'addVop',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'agentRegistrationFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'agents',
    outputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'eloRating', internalType: 'uint32', type: 'uint32' },
      { name: 'totalWins', internalType: 'uint32', type: 'uint32' },
      { name: 'totalLosses', internalType: 'uint32', type: 'uint32' },
      { name: 'totalStaked', internalType: 'uint256', type: 'uint256' },
      { name: 'totalWon', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'agentsCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'battleCreationFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'battleImplementation',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'battles',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'battlesCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'challengerId', internalType: 'uint256', type: 'uint256' },
      {
        name: 'config',
        internalType: 'struct ClawttackTypes.BattleConfig',
        type: 'tuple',
        components: [
          { name: 'stake', internalType: 'uint256', type: 'uint256' },
          { name: 'warmupBlocks', internalType: 'uint32', type: 'uint32' },
          { name: 'targetAgentId', internalType: 'uint256', type: 'uint256' },
          { name: 'maxJokers', internalType: 'uint8', type: 'uint8' },
        ],
      },
    ],
    name: 'createBattle',
    outputs: [
      { name: 'battleAddress', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [{ name: 'index', internalType: 'uint8', type: 'uint8' }],
    name: 'deactivateVop',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    name: 'deactivatedVOPs',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'index', internalType: 'uint8', type: 'uint8' }],
    name: 'getVopByIndex',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getVopCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'index', internalType: 'uint8', type: 'uint8' }],
    name: 'isVopActive',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'isVopRegistered',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pendingOwner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'protocolFeeRate',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'protocolFees',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'registerAgent',
    outputs: [{ name: 'agentId', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '_fee', internalType: 'uint256', type: 'uint256' }],
    name: 'setAgentRegistrationFee',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '_fee', internalType: 'uint256', type: 'uint256' }],
    name: 'setBattleCreationFee',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '_impl', internalType: 'address', type: 'address' }],
    name: 'setBattleImplementation',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '_rate', internalType: 'uint256', type: 'uint256' }],
    name: 'setProtocolFeeRate',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'battleId', internalType: 'uint256', type: 'uint256' },
      { name: 'winnerId', internalType: 'uint256', type: 'uint256' },
      { name: 'loserId', internalType: 'uint256', type: 'uint256' },
      { name: 'battleStake', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'settleBattle',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'totalVolume',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'vopRegistry',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'to', internalType: 'address payable', type: 'address' }],
    name: 'withdrawFees',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'wordDictionary',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'agentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'AgentRegistered',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'oldFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'newFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'AgentRegistrationFeeUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'battleId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'challengerId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'stake',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'targetAgentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'BattleCreated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'oldFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'newFee',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'BattleCreationFeeUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferStarted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'oldRate',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'newRate',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'ProtocolFeeUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'agentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'newRating',
        internalType: 'uint32',
        type: 'uint32',
        indexed: false,
      },
    ],
    name: 'RatingUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'vopAddress',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'VOPAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'index', internalType: 'uint8', type: 'uint8', indexed: true },
      {
        name: 'vopAddress',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'VOPDeactivated',
  },
  { type: 'error', inputs: [], name: 'ConfigOutOfBounds' },
  { type: 'error', inputs: [], name: 'ERC1167FailedCreateClone' },
  { type: 'error', inputs: [], name: 'FeeTooHigh' },
  { type: 'error', inputs: [], name: 'InsufficientValue' },
  { type: 'error', inputs: [], name: 'InvalidCall' },
  { type: 'error', inputs: [], name: 'NotAgentOwner' },
  { type: 'error', inputs: [], name: 'NotParticipant' },
  {
    type: 'error',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'OwnableInvalidOwner',
  },
  {
    type: 'error',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
  },
  { type: 'error', inputs: [], name: 'ReentrancyGuardReentrantCall' },
  { type: 'error', inputs: [], name: 'TransferFailed' },
  { type: 'error', inputs: [], name: 'VOPAlreadyRegistered' },
  { type: 'error', inputs: [], name: 'VopIndexOutOfRange' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ClawttackBattle
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const clawttackBattleAbi = [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    inputs: [],
    name: 'BPS_DENOMINATOR',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'COMPROMISE_REASON',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'DOMAIN_TYPE_INIT',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'DOMAIN_TYPE_TURN',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'JOKER_NARRATIVE_LEN',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_NARRATIVE_LEN',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_POISON_WORD_LEN',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MIN_POISON_WORD_LEN',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '_acceptorId', internalType: 'uint256', type: 'uint256' }],
    name: 'acceptBattle',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'acceptorId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'acceptorOwner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'arena',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'battleId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'cancelBattle',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'signature', internalType: 'bytes', type: 'bytes' }],
    name: 'captureFlag',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'captureFlag',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'challengerId',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'challengerOwner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'claimTimeoutWin',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'clock',
    outputs: [
      { name: 'bankA', internalType: 'uint128', type: 'uint128' },
      { name: 'bankB', internalType: 'uint128', type: 'uint128' },
      { name: 'lastTurnBlock', internalType: 'uint64', type: 'uint64' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'config',
    outputs: [
      { name: 'stake', internalType: 'uint256', type: 'uint256' },
      { name: 'warmupBlocks', internalType: 'uint32', type: 'uint32' },
      { name: 'targetAgentId', internalType: 'uint256', type: 'uint256' },
      { name: 'maxJokers', internalType: 'uint8', type: 'uint8' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'currentTurn',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'firstMoverA',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getBattleState',
    outputs: [
      {
        name: '_phase',
        internalType: 'enum ClawttackBattle.BattlePhase',
        type: 'uint8',
      },
      { name: '_currentTurn', internalType: 'uint32', type: 'uint32' },
      { name: '_bankA', internalType: 'uint128', type: 'uint128' },
      { name: '_bankB', internalType: 'uint128', type: 'uint128' },
      { name: '_sequenceHash', internalType: 'bytes32', type: 'bytes32' },
      { name: '_battleId', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '_arena', internalType: 'address', type: 'address' },
      { name: '_battleId', internalType: 'uint256', type: 'uint256' },
      { name: '_challengerId', internalType: 'uint256', type: 'uint256' },
      { name: '_challengerOwner', internalType: 'address', type: 'address' },
      {
        name: '_config',
        internalType: 'struct ClawttackTypes.BattleConfig',
        type: 'tuple',
        components: [
          { name: 'stake', internalType: 'uint256', type: 'uint256' },
          { name: 'warmupBlocks', internalType: 'uint32', type: 'uint32' },
          { name: 'targetAgentId', internalType: 'uint256', type: 'uint256' },
          { name: 'maxJokers', internalType: 'uint8', type: 'uint8' },
        ],
      },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'jokersRemainingA',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'jokersRemainingB',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'nccResultA',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'nccResultAReady',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'nccResultB',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'nccResultBReady',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pendingNccA',
    outputs: [
      { name: 'commitment', internalType: 'bytes32', type: 'bytes32' },
      { name: 'defenderGuessIdx', internalType: 'uint8', type: 'uint8' },
      { name: 'hasDefenderGuess', internalType: 'bool', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pendingNccB',
    outputs: [
      { name: 'commitment', internalType: 'bytes32', type: 'bytes32' },
      { name: 'defenderGuessIdx', internalType: 'uint8', type: 'uint8' },
      { name: 'hasDefenderGuess', internalType: 'bool', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pendingVopA',
    outputs: [
      { name: 'commitment', internalType: 'bytes32', type: 'bytes32' },
      { name: 'solverClaimedIndex', internalType: 'uint8', type: 'uint8' },
      { name: 'solverSolution', internalType: 'bytes', type: 'bytes' },
      { name: 'commitBlockNumber', internalType: 'uint64', type: 'uint64' },
      { name: 'solverPassed', internalType: 'bool', type: 'bool' },
      { name: 'hasSolverResponse', internalType: 'bool', type: 'bool' },
      { name: 'instanceCommit', internalType: 'bytes32', type: 'bytes32' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'pendingVopB',
    outputs: [
      { name: 'commitment', internalType: 'bytes32', type: 'bytes32' },
      { name: 'solverClaimedIndex', internalType: 'uint8', type: 'uint8' },
      { name: 'solverSolution', internalType: 'bytes', type: 'bytes' },
      { name: 'commitBlockNumber', internalType: 'uint64', type: 'uint64' },
      { name: 'solverPassed', internalType: 'bool', type: 'bool' },
      { name: 'hasSolverResponse', internalType: 'bool', type: 'bool' },
      { name: 'instanceCommit', internalType: 'bytes32', type: 'bytes32' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'phase',
    outputs: [
      {
        name: '',
        internalType: 'enum ClawttackBattle.BattlePhase',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'poisonWord',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'to', internalType: 'address payable', type: 'address' }],
    name: 'rescueStuckFunds',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'sequenceHash',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'startBlock',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'state',
    outputs: [
      {
        name: '',
        internalType: 'enum ClawttackTypes.ResultType',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'payload',
        internalType: 'struct ClawttackTypes.TurnPayload',
        type: 'tuple',
        components: [
          { name: 'narrative', internalType: 'string', type: 'string' },
          { name: 'customPoisonWord', internalType: 'string', type: 'string' },
          {
            name: 'nccAttack',
            internalType: 'struct ClawttackTypes.NccAttack',
            type: 'tuple',
            components: [
              {
                name: 'candidateWordIndices',
                internalType: 'uint16[4]',
                type: 'uint16[4]',
              },
              {
                name: 'candidateOffsets',
                internalType: 'uint16[4]',
                type: 'uint16[4]',
              },
              {
                name: 'nccCommitment',
                internalType: 'bytes32',
                type: 'bytes32',
              },
            ],
          },
          {
            name: 'nccDefense',
            internalType: 'struct ClawttackTypes.NccDefense',
            type: 'tuple',
            components: [
              { name: 'guessIdx', internalType: 'uint8', type: 'uint8' },
            ],
          },
          {
            name: 'nccReveal',
            internalType: 'struct ClawttackTypes.NccReveal',
            type: 'tuple',
            components: [
              { name: 'salt', internalType: 'bytes32', type: 'bytes32' },
              { name: 'intendedIdx', internalType: 'uint8', type: 'uint8' },
            ],
          },
          {
            name: 'vopCommit',
            internalType: 'struct ClawttackTypes.VopCommit',
            type: 'tuple',
            components: [
              {
                name: 'vopCommitment',
                internalType: 'bytes32',
                type: 'bytes32',
              },
              {
                name: 'instanceCommit',
                internalType: 'bytes32',
                type: 'bytes32',
              },
            ],
          },
          {
            name: 'vopSolve',
            internalType: 'struct ClawttackTypes.VopSolve',
            type: 'tuple',
            components: [
              { name: 'vopClaimedIndex', internalType: 'uint8', type: 'uint8' },
              { name: 'solution', internalType: 'bytes', type: 'bytes' },
            ],
          },
          {
            name: 'vopReveal',
            internalType: 'struct ClawttackTypes.VopReveal',
            type: 'tuple',
            components: [
              { name: 'vopSalt', internalType: 'bytes32', type: 'bytes32' },
              { name: 'vopIndex', internalType: 'uint8', type: 'uint8' },
            ],
          },
        ],
      },
    ],
    name: 'submitTurn',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'targetWordIndex',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'totalPot',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'battleId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'acceptorId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'challengerGoesFirst',
        internalType: 'bool',
        type: 'bool',
        indexed: false,
      },
    ],
    name: 'BattleAccepted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'battleId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'BattleCancelled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'battleId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'winnerId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'loserId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'resultType',
        internalType: 'enum ClawttackTypes.ResultType',
        type: 'uint8',
        indexed: false,
      },
    ],
    name: 'BattleSettled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'battleId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'winnerId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'loserId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'FlagCaptured',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'version',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
    ],
    name: 'Initialized',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'battleId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'agentId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'jokersRemaining',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
    ],
    name: 'JokerPlayed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'battleId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      { name: 'turn', internalType: 'uint32', type: 'uint32', indexed: false },
      {
        name: 'defenderCorrect',
        internalType: 'bool',
        type: 'bool',
        indexed: false,
      },
      {
        name: 'newBank',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
    ],
    name: 'NccResolved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'battleId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'claimantId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'TimeoutClaimed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'battleId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'playerId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'turnNumber',
        internalType: 'uint32',
        type: 'uint32',
        indexed: false,
      },
      {
        name: 'sequenceHash',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
      {
        name: 'targetWord',
        internalType: 'uint16',
        type: 'uint16',
        indexed: false,
      },
      {
        name: 'poisonWord',
        internalType: 'string',
        type: 'string',
        indexed: false,
      },
      {
        name: 'narrative',
        internalType: 'string',
        type: 'string',
        indexed: false,
      },
      {
        name: 'bankA',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
      {
        name: 'bankB',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
    ],
    name: 'TurnSubmitted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'battleId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      { name: 'turn', internalType: 'uint32', type: 'uint32', indexed: false },
      {
        name: 'outcome',
        internalType: 'enum ClawttackTypes.VopOutcome',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'challengerVopIndex',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'solverClaimedIndex',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'bankA',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
      {
        name: 'bankB',
        internalType: 'uint128',
        type: 'uint128',
        indexed: false,
      },
    ],
    name: 'VopResolved',
  },
  { type: 'error', inputs: [], name: 'BattleNotActive' },
  { type: 'error', inputs: [], name: 'BattleNotCancellable' },
  { type: 'error', inputs: [], name: 'BattleNotOpen' },
  { type: 'error', inputs: [], name: 'CandidateNotInNarrative' },
  { type: 'error', inputs: [], name: 'CannotBattleSelf' },
  { type: 'error', inputs: [], name: 'DeadlineNotExpired' },
  { type: 'error', inputs: [], name: 'DuplicateCandidate' },
  { type: 'error', inputs: [], name: 'ECDSAInvalidSignature' },
  {
    type: 'error',
    inputs: [{ name: 'length', internalType: 'uint256', type: 'uint256' }],
    name: 'ECDSAInvalidSignatureLength',
  },
  {
    type: 'error',
    inputs: [{ name: 's', internalType: 'bytes32', type: 'bytes32' }],
    name: 'ECDSAInvalidSignatureS',
  },
  { type: 'error', inputs: [], name: 'EloDifferenceTooHigh' },
  { type: 'error', inputs: [], name: 'InsufficientValue' },
  { type: 'error', inputs: [], name: 'InvalidASCII' },
  { type: 'error', inputs: [], name: 'InvalidCompromiseSignature' },
  { type: 'error', inputs: [], name: 'InvalidGuessIndex' },
  { type: 'error', inputs: [], name: 'InvalidInitialization' },
  { type: 'error', inputs: [], name: 'InvalidPoisonWord' },
  { type: 'error', inputs: [], name: 'MissingCommitment' },
  { type: 'error', inputs: [], name: 'NarrativeTooLong' },
  { type: 'error', inputs: [], name: 'NarrativeTooShort' },
  { type: 'error', inputs: [], name: 'NoJokersRemaining' },
  { type: 'error', inputs: [], name: 'NoSecretCommitted' },
  { type: 'error', inputs: [], name: 'NotInitializing' },
  { type: 'error', inputs: [], name: 'NotParticipant' },
  { type: 'error', inputs: [], name: 'PoisonWordDetected' },
  { type: 'error', inputs: [], name: 'TargetWordMissing' },
  { type: 'error', inputs: [], name: 'TransferFailed' },
  { type: 'error', inputs: [], name: 'TurnTooFast' },
  { type: 'error', inputs: [], name: 'UnauthorizedTurn' },
  { type: 'error', inputs: [], name: 'WrongTargetAgent' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IClawttackArenaCallback
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const iClawttackArenaCallbackAbi = [
  {
    type: 'function',
    inputs: [
      { name: 'battleId', internalType: 'uint256', type: 'uint256' },
      { name: 'winnerId', internalType: 'uint256', type: 'uint256' },
      { name: 'loserId', internalType: 'uint256', type: 'uint256' },
      { name: 'stake', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'settleBattle',
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IClawttackArenaView
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const iClawttackArenaViewAbi = [
  {
    type: 'function',
    inputs: [],
    name: 'MAX_ELO_DIFF',
    outputs: [{ name: '', internalType: 'uint32', type: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MIN_RATED_STAKE',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'agentId', internalType: 'uint256', type: 'uint256' }],
    name: 'agents',
    outputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'eloRating', internalType: 'uint32', type: 'uint32' },
      { name: 'totalWins', internalType: 'uint32', type: 'uint32' },
      { name: 'totalLosses', internalType: 'uint32', type: 'uint32' },
      { name: 'totalStaked', internalType: 'uint256', type: 'uint256' },
      { name: 'totalWon', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'index', internalType: 'uint8', type: 'uint8' }],
    name: 'getVopByIndex',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getVopCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'index', internalType: 'uint8', type: 'uint8' }],
    name: 'isVopActive',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'protocolFeeRate',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'wordDictionary',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IClawttackBattle
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const iClawttackBattleAbi = [
  {
    type: 'function',
    inputs: [
      { name: '_arena', internalType: 'address', type: 'address' },
      { name: '_battleId', internalType: 'uint256', type: 'uint256' },
      { name: '_challengerId', internalType: 'uint256', type: 'uint256' },
      { name: '_challengerOwner', internalType: 'address', type: 'address' },
      {
        name: '_config',
        internalType: 'struct ClawttackTypes.BattleConfig',
        type: 'tuple',
        components: [
          { name: 'stake', internalType: 'uint256', type: 'uint256' },
          { name: 'warmupBlocks', internalType: 'uint32', type: 'uint32' },
          { name: 'targetAgentId', internalType: 'uint256', type: 'uint256' },
          { name: 'maxJokers', internalType: 'uint8', type: 'uint8' },
        ],
      },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IVerifiableOraclePrimitive
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const iVerifiableOraclePrimitiveAbi = [
  {
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [
      { name: 'params', internalType: 'bytes', type: 'bytes' },
      { name: 'solution', internalType: 'bytes', type: 'bytes' },
      { name: 'referenceBlock', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'verify',
    outputs: [{ name: 'isValid', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'error',
    inputs: [{ name: 'reason', internalType: 'string', type: 'string' }],
    name: 'VerificationFailed',
  },
] as const
